### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by DavidBerdik** [99keshav99/CaptureSposed#11]
The README can be updated with some additional documentation.

**Comment by Zaelot** [comment]
Could the link to the LSPosed be added to the readme as well, so users know what is supposed to be installed? (I belive it's about this: https://github.com/LSPosed/LSPosed )

**Comment by DavidBerdik** [comment]
@Zaelot The README did at one point have a link to the official LSPosed download but I recently chose to remove it because the official LSPosed release no longer works properly on many devices running the latest versions of Android. Many users, including me, are relying on one of several forks and I do not feel comfortable with the idea of suggesting the use of a specific fork nor do I feel comfortable with suggesting the use of the official release given that it is outdated.
