### ISSUE TITLE
problem with parsing package

### ISSUE THREAD

**Issue by kersvanbinsbergen** [99keshav99/CaptureSposed#52]
Says the aAndroid Iinstaller.
Apk pure says: file is incomplete

**Comment by DavidBerdik** [comment]
I have looked in to this and determined that it is an issue with the APKPure download link. The APKPure download link is not controlled by us. Please download and install CaptureSposed from one of the distribution channels listed [here](https://github.com/99keshav99/CaptureSposed).

**Comment by kersvanbinsbergen** [comment]
I downloaded from github.

I used apk pure as aa test to run the installer for the apk

**Comment by DavidBerdik** [comment]
I just tested downloading the GitHub distribution and installing it via the APKPure app and it worked just fine. My guess is that your download of the APK was probably interrupted and you ended up with an incomplete file. I would suggest trying again.

Also, this is not directly related to your issue, but there are other options for sideloading APKs if you would prefer to not use the bloatware trash that is APKPure. 🙂

![Screenshot_20240606-155249](https://github.com/99keshav99/CaptureSposed/assets/7663225/0f147097-e572-444f-9c5d-a3b30cb8be4f)

![Screenshot_20240606-155310](https://github.com/99keshav99/CaptureSposed/assets/7663225/376137ce-ee05-49b2-8b76-23c757a4ae54)
