### ISSUE TITLE
Wechat knows that I am taking screenshots.

### ISSUE THREAD

**Issue by soulpursuit** [99keshav99/CaptureSposed#55]
![Screenshot_2024-06-13-02-37-11-426_com tencent mm](https://github.com/99keshav99/CaptureSposed/assets/48674277/856a7326-feac-40e5-8f5a-6cf4ef10dde1)

![Screenshot_2024-06-13-02-41-20-570_com android shell](https://github.com/99keshav99/CaptureSposed/assets/48674277/72824924-75df-4ab4-8648-4a1639f9ae05)

When I take a screenshot in the QR code interface of WeChat, it can still know that I took a screenshot, which is very sad.

**Comment by tomaszk8266** [comment]
So it probably uses one of the pre-A14 screenshot detection solutions. CaptureSposed doesn't support blocking them currently, but it may change in future (#46).

**Comment by DavidBerdik** [comment]
My guess is that WeChat probably uses the pre-Android 14 method for screenshot detection as discussed in issue #46. If you are willing and able to do further research on this, that would be great!

**Comment by soulpursuit** [comment]
> My guess is that WeChat probably uses the pre-Android 14 method for screenshot detection as discussed in issue #46. If you are willing and able to do further research on this, that would be great!

Let you down, I'm not a professional developer. I can only be regarded as an experienced user.

**Comment by DavidBerdik** [comment]
> Let you down, I'm not a professional developer. I can only be regarded as an experienced user.

That's fine! In that case, please either wait until this feature gets added to CaptureSposed or use the Storage Isolation workaround I mentioned in #46.

> It is already possible to bypass screenshot detection for apps that use this approach by leveraging [Storage Isolation](https://sr.rikka.app/) to blacklist access to the Screenshots directory, but building this functionality directly into CaptureSposed would make it much more user-friendly.

**Comment by DavidBerdik** [comment]
Since the addition of support for blocking pre-Android 14 detection methods is already tracked by #46, I am going to close this.
