### ISSUE TITLE
Wechat still knows, and I took a screenshot.

### ISSUE THREAD

**Issue by soulpursuit** [99keshav99/CaptureSposed#56]
![Screenshot_2024-06-13-02-37-11-426_com tencent mm](https://github.com/99keshav99/CaptureSposed/assets/48674277/856a7326-feac-40e5-8f5a-6cf4ef10dde1)

![Screenshot_2024-06-13-02-41-20-570_com android shell](https://github.com/99keshav99/CaptureSposed/assets/48674277/72824924-75df-4ab4-8648-4a1639f9ae05)

When I take a screenshot in the QR code interface of WeChat, it can still know that I took a screenshot, which is very sad.

**Comment by tomaszk8266** [comment]
Please don't spam by creating multiple issues for same problem
